### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by pixnlove** [garronej/react-dsfr-next-demo#1]
When using Jest as a test runner, we are encountering an issue of compilation `Cannot use import statement outside a module` by importing a component like that: `import { Alert } from "@codegouvfr/react-dsfr/Alert";`.
You can take a look to this repository to see the error: [https://github.com/DISIC/next-with-jest](https://github.com/DISIC/next-with-jest), just install packages with `npm i` and run the tests `npm run test`.

**Comment by garronej** [comment]
@pixnlove Thank you very much for taking the time to setup a reproduction repo.  
I'll come back with a solution ASAP.

**Comment by garronej** [comment]
Hi @pixnlove,  
I eventually decided against shiping a CJS distribution only so that jest can be suported out of the box because it's capable of transpiling things itself.  
I submited a PR on your repo https://github.com/DISIC/monfranceconnect/pull/33  

And documented how to setup jest for Next and CRA (I think vite users will use vitest):  
https://react-dsfr.etalab.studio/

**Comment by pixnlove** [comment]
Hey @garronej, thanks a lot for your reactivity!
This solution is working well with npm but not with pnpm, i'm taking a look why.

**Comment by garronej** [comment]
Strange... I tested with pnpm I think...

**Comment by garronej** [comment]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/6702424/222746978-49b7f933-d401-49bf-ab87-d94ea4e12184.png">

**Comment by pixnlove** [comment]
Maybe this branch is not using a React-dsfr component import?

**Comment by garronej** [comment]
Shit, indeed.  Sorry about that.  
I got the setup working with a vanilla Next.js repo and a vanilla CRA project but your setup is a bit less standard.

**Comment by pixnlove** [comment]
Take a look here [https://github.com/DISIC/next-with-jest](https://github.com/DISIC/next-with-jest), I updated it with your suggested Jest configuration and the test is failing with `pnpm` but not `npm`. I found a quick win but its slower:
`config.transformIgnorePatterns = ["//node_modules"];`
I just replaced the slash with a double one. Maybe commonJS could be simpler and compatible with all projects finally? 😬

**Comment by garronej** [comment]
I got confused this morning.... 
Everything works out of the box assuming you are using `next/jest` as sugested in the Next documentation: https://nextjs.org/docs/testing  

I just updated my PR and removed the misleading documentation.

**Comment by pixnlove** [comment]
Well done @garronej, sorry for not implementing `next/jest` as recommended by the Next documentation and thanks you a lot again.

**Comment by garronej** [comment]
No problem, you did well rising the issue.  
To be honest I did update something that ended up making it work.  
It wouldn't have worked with `next-transpile-modules`. I figured out it was no longer required thanks to you.
